version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
    - 80:80
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
    - app

  app:
    container_name: apache-jena-fuseki-4.1.0
    restart: always
    environment: 
      - JAVA_OPTIONS=-Xmx1048m
    build: ./
    working_dir: /app
    ports:
      - "3030:3030"
    expose:
      - "3030"
    volumes:
      - /Users/sarbajitdutta/Documents/VIVO/home/tdbContentModels:/app/tdbContentModels