apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: vivo-fuseki
  namespace: reciter
  labels:
    app: vivo-fuseki
    environment: dev
    tier: backend
    owner: szd2013
spec:
  selector:
    matchLabels:
      app: vivo-fuseki
      environment: dev
      tier: backend
      owner: szd2013
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: vivo-fuseki
        environment: dev
        tier: backend
        owner: szd2013
    spec:
      containers:
      - image: 665083158573.dkr.ecr.us-east-1.amazonaws.com/wcmc/vivo/fuseki:latest
        name: vivo-fuseki
        imagePullPolicy: Always
        env:
        ports:
        - containerPort: 3030
          name: vivo-fuseki
        resources:
          requests:
            memory: 6G
            cpu: 1
          limits:
            memory: 6G
            cpu: 1
        livenessProbe:
          httpGet:
            path: "/$/ping"
            port: 3030
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: "/$/ping"
            port: 3030
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
         - name: vivo-fuseki-pvc
           mountPath: /app/tdbContentModels
      - image: nginx:alpine
        name:  nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: "/nginx-health"
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: "/nginx-health"
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 1
          failureThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
          - name:  nginx-conf
            mountPath:  /etc/nginx/conf.d
      nodeSelector:
        eks.amazonaws.com/capacityType: ON_DEMAND
      volumes:
        - name: vivo-fuseki-pvc 
          persistentVolumeClaim:
            claimName: vivo-fuseki-tdb-pvc
        - name: nginx-conf  
          configMap:
            name: vivo-fuseki-nginx-configmap