apiVersion: v1
kind: ConfigMap
metadata:
  name: vivo-fuseki-nginx-configmap
  namespace: reciter
  labels:
    app: vivo-fuseki
    environment: dev
    tier: backend
    owner: szd2013
data:
  nginx.conf: |-
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        fastcgi_buffers 16 32k;
        fastcgi_buffer_size 32k;

        client_body_buffer_size 250M;

        client_header_buffer_size 5120k;
        large_client_header_buffers 16 5120k;

        location / {
            client_max_body_size 0;
            rewrite ^/fuseki/(.*)$ /$1 break;
            proxy_pass http://localhost:3030;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /nginx-health {
            access_log off;
            return 200;
        }
    }