apiVersion: v1
kind: Service
metadata:
  name: vivo-fuseki
  namespace: reciter
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /$/ping
    alb.ingress.kubernetes.io/success-codes: 200-302
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-port: '80'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
  labels:
    app: vivo-fuseki
    environment: dev
    tier: backend
    owner: szd2013
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: vivo-fuseki
    tier: backend
  type: NodePort