apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vivo-fuseki-tdb-pvc
  namespace: reciter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 100Gi